# Generated by Django 6.0.3 on 2026-03-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('page_id', models.CharField(max_length=100)),
                ('page_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('ad_text', models.TextField(blank=True, null=True)),
                ('snapshot_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('publisher_platforms', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('raw_ads', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
